# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
development:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d858fm89smvuil
  username: oxegyibtmwkypk
  password: 'E2-Okd61HjeM6_O06lA6ts0kzG'
  host: ec2-107-20-165-44.compute-1.amazonaws.com
  port: 5432
#in sockets, so uncomment these lines.
  host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  #port: 5432

  # Schema search path. The server defaults to $user,public
  #schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  #min_messages: notice

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: d4239650374gfc
  username: xlbnccbjlsedci
  password: 'WDMadnoD3a-7eSfhLIpz4Ot6Jb'
  host: ec2-54-225-106-227.compute-1.amazonaws.com
  port: 5432

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: dl4d7v31a0br5
  username: nixlgwnlystffq
  password: '-3q5mYmnmr5DMHedhQ_Lxt9urN'
  host: ec2-54-225-106-227.compute-1.amazonaws.com
  port: 5432
